### ISSUE TITLE
Crash when triggering api twice

### ISSUE THREAD

**Issue by dreyrz** [dreyrz/flutter_otp_autofill_package#1]
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever(13409): Waiting for SMS
D/AndroidRuntime(13409): Shutting down VM
E/AndroidRuntime(13409): FATAL EXCEPTION: main
E/AndroidRuntime(13409): Process: com.votorantim.bvpd.uat, PID: 13409
E/AndroidRuntime(13409): java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=com.votorantim.bvpd.uat (has extras) } in com.otp.autofill.otp_autofill_package.FlutterSmsRetriever@fc6950a
E/AndroidRuntime(13409): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
E/AndroidRuntime(13409): 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(13409): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(13409): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13409): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(13409): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(13409): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(13409): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13409): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(13409): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(13409): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
E/AndroidRuntime(13409): 	at java.lang.Class.isAssignableFrom(Class.java:589)
E/AndroidRuntime(13409): 	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4897)
E/AndroidRuntime(13409): 	at android.os.Parcel.readParcelableInternal(Parcel.java:4804)
E/AndroidRuntime(13409): 	at android.os.Parcel.readValue(Parcel.java:4564)
E/AndroidRuntime(13409): 	at android.os.Parcel.readValue(Parcel.java:4347)
E/AndroidRuntime(13409): 	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
E/AndroidRuntime(13409): 	at android.os.Parcel$LazyValue.apply(Parcel.java:4442)
E/AndroidRuntime(13409): 	at android.os.Parcel$LazyValue.apply(Parcel.java:4401)
E/AndroidRuntime(13409): 	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
E/AndroidRuntime(13409): 	at android.os.BaseBundle.getValue(BaseBundle.java:374)
E/AndroidRuntime(13409): 	at android.os.BaseBundle.getValue(BaseBundle.java:357)
E/AndroidRuntime(13409): 	at android.os.BaseBundle.get(BaseBundle.java:696)
E/AndroidRuntime(13409): 	at android.os.Bundle.getParcelable(Bundle.java:953)
E/AndroidRuntime(13409): 	at com.otp.autofill.otp_autofill_package.FlutterSmsRetriever.onReceive(FlutterSmsRetriever.kt:8)
E/AndroidRuntime(13409): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
E/AndroidRuntime(13409): 	... 9 more
D/libcrashlytics(13409): Initializing libcrashlytics version 3.2.0
D/libcrashlytics(13409): Initializing native crash handling successful.
I/Process (13409): Sending signal. PID: 13409 SIG: 9
Lost connection to device.
Exited

**Comment by dreyrz** [comment]
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): Waiting for SMS
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): onReceive java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at java.lang.Class.isAssignableFrom(Class.java:589)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4897)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.Parcel.readParcelableInternal(Parcel.java:4804)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.Parcel.readValue(Parcel.java:4564)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.Parcel.readValue(Parcel.java:4347)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.Parcel$LazyValue.apply(Parcel.java:4442)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.Parcel$LazyValue.apply(Parcel.java:4401)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.BaseBundle.getValue(BaseBundle.java:374)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.BaseBundle.getValue(BaseBundle.java:357)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.BaseBundle.get(BaseBundle.java:696)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.Bundle.getParcelable(Bundle.java:953)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at com.otp.autofill.otp_autofill_package.FlutterSmsRetriever.onReceive(FlutterSmsRetriever.kt:8)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.Handler.handleCallback(Handler.java:942)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.Looper.loopOnce(Looper.java:201)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.os.Looper.loop(Looper.java:288)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at java.lang.reflect.Method.invoke(Native Method)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/com.otp.autofill.otp_autofill_package.FlutterSmsRetriever( 4709): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
